### ISSUE TITLE
Problem of files missing

### ISSUE THREAD

**Issue by ShawLen** [zhuliwen/RoadnetSZ#3]
Hello, I find that deeplight_agent, map_computor, and cityflow_agent are missing in Hi-Light, could u please provide these files? Thanks!

**Comment by waunx** [comment]
same question tut

**Comment by Mamo666** [comment]
似乎是被编译后放在了pycache文件夹里，希望作者能开源这部分代码 : )

**Comment by zhuliwen** [comment]
Apologies for the late response. The HiLight author has supplemented this section of the code. The link is:

[cityflow_agent.py](https://github.com/zhuliwen/RoadnetSZ/blob/main/code/HiLight/cityflow_agent.py)



I hope this is helpful to you :).
