### ISSUE TITLE
Incomplete code of HiLight

### ISSUE THREAD

**Issue by LiangZhang1996** [zhuliwen/RoadnetSZ#4]
The code for HiLight is incomplete and cannot perform all its intended functions.

**Comment by zhuliwen** [comment]
Apologies for the late response. The HiLight author has supplemented this section of the code. The link is:

[cityflow_agent.py](https://github.com/zhuliwen/RoadnetSZ/blob/main/code/HiLight/cityflow_agent.py)



I hope this is helpful to you :).

**Comment by LiangZhang1996** [comment]
Thanks
